package io.github.amarcinkowski.c64.asm;

/**
 * Based on 6502/6510/8500/8502 Opcode matrix (http://www.oxyron.de/html/opcodes02.html)
 */
public enum Mnemonic {
    ADC("adc","ADd with Carry"),
    ANC("anc",""),
    AND("and","bitwise AND with accumulator"),
    ANE("ane",""),
    ARR("arr",""),
    ASL("asl","Arithmetic Shift Left"),
    ASR("asr",""),
    BCC("bcc","Branch on Carry Clear "),
    BCS("bcs","Branch on Carry Set "),
    BEQ("beq","Branch on EQual "),
    BIT("bit","test BITs"),
    BMI("bmi","Branch on MInus "),
    BNE("bne","Branch on Not Equal "),
    BPL("bpl","Branch on PLus "),
    BRK("brk","BReaK"),
    BVC("bvc","Branch on oVerflow Clear"),
    BVS("bvs","Branch on oVerflow Set "),
    CLC("clc","CLear Carry "),
    CLD("cld","CLear Decimal "),
    CLI("cli","CLear Interrupt "),
    CLV("clv","CLear oVerflow "),
    CMP("cmp","CoMPare accumulator"),
    CPX("cpx","ComPare X register"),
    CPY("cpy","ComPare Y register"),
    DCP("dcp",""),
    DEC("dec","DECrement memory"),
    DEX("dex","DEcrement X "),
    DEY("dey","DEcrement Y "),
    EOR("eor","bitwise Exclusive OR"),
    INC("inc","INCrement memory"),
    INX("inx","INcrement X "),
    INY("iny","INcrement Y "),
    ISB("isb",""),
    JAM("jam",""),
    JMP("jmp","JuMP"),
    JSR("jsr","Jump to SubRoutine"),
    LAE("lae",""),
    LAX("lax",""),
    LDA("lda","LoaD Accumulator"),
    LDX("ldx","LoaD X register"),
    LDY("ldy","LoaD Y register"),
    LSR("lsr","Logical Shift Right"),
    LXA("lxa",""),
    NOP("nop","No OPeration"),
    ORA("ora","bitwise OR with Accumulator"),
    PHA("pha","PusH Accumulator "),
    PHP("php","PusH Processor status "),
    PLA("pla","PuLl Accumulator "),
    PLP("plp","PuLl Processor status "),
    RLA("rla",""),
    ROL("rol","ROtate Left"),
    ROR("ror","ROtate Right"),
    RRA("rra",""),
    RTI("rti","ReTurn from Interrupt"),
    RTS("rts","ReTurn from Subroutine"),
    SAX("sax",""),
    SBC("sbc","SuBtract with Carry"),
    SBX("sbx",""),
    SEC("sec","SEt Carry "),
    SED("sed","SEt Decimal "),
    SEI("sei","SEt Interrupt "),
    SHA("sha",""),
    SHS("shs",""),
    SHX("shx",""),
    SHY("shy",""),
    SLO("slo",""),
    SRE("sre",""),
    STA("sta","STore Accumulator"),
    STX("stx","STore X register"),
    STY("sty","STore Y register"),
    TAX("tax","Transfer A to X "),
    TAY("tay","Transfer A to Y "),
    TSX("tsx","Transfer Stack ptr to X "),
    TXA("txa","Transfer X to A "),
    TXS("txs","Transfer X to Stack ptr "),
    TYA("tya","Transfer Y to A "),
    ;
    public String mnemonic;

    Mnemonic(String mnemonic, String description) {
        this.mnemonic = mnemonic;
    }
}


